export const MAP_FETCH_GOLOS_BLOG = 'MAP_FETCH_GOLOS_BLOG';
export const SAVE_FILTERING_AND_ORDERING_DATA = 'SAVE_FILTERING_AND_ORDERING_DATA'
export const LOGIN_GOLOS = 'LOGIN_GOLOS';
export const ASK_GOLOS = 'ASK_GOLOS';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';
