version: '3'
services:
  mysql-dev:
    image: 'mysql:8.0.2'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project2
    ports:
      - '3306:3306'
    volumes:
      - './my.conf:/etc/mysql/conf.d/config-file.cnf'
      - './data:/var/lib/mysql:rw'
  client:
    build: ../../../
    links:
      - mysql-dev
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql-dev/project2?useUnicode=true&characterEncoding=utf8&useSSL=false'
    depends_on:
      - mysql-dev
    ports:
      - '8080:8080'
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - ./code:/var/www/html/site1
      - './default.conf:/etc/nginx/conf.d/default.conf'
    links:
      - client
    depends_on:
      - client

