export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const DELETE_CURRENT_USER = 'DELETE_CURRENT_USER';
export const SET_CURRENT_USER_FROM_TOKEN = 'SET_CURRENT_USER_FROM_TOKEN';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';
export const UNAUTHORIZED = '_UNAUTHORIZED';
export const LOGIN_GOLOS = 'LOGIN_GOLOS';
