version: '2'
services:
    project2-app:
        image: project2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://project2-mysql:3306/project2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    project2-mysql:
        extends:
            file: mysql.yml
            service: project2-mysql
