export const FETCH_GOLOS_SINGLE_POST_POST = 'FETCH_GOLOS_SINGLE_POST_POST';
export const FETCH_GOLOS_SINGLE_POST_COMMENTS = 'FETCH_GOLOS_SINGLE_POST_COMMENTS';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';
