export const FETCH_MY_QUESTIONS = 'FETCH_MY_QUESTIONS';
export const SAVE_FILTERING_AND_ORDERING_DATA_MY_QUESTIONS = 'SAVE_FILTERING_AND_ORDERING_DATA_MY_QUESTIONS';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';
